export const SUPABASE_URL = import.meta.env.NEXT_PUBLIC_SUPABASE_URL
export const SUPABASE_ANON_KEY = import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
export const SUPABASE_FUNCTIONS_BASE_URL = import.meta.env
  .NEXT_PUBLIC_FUNCTIONS_BASE_URL
