name: Check Code Formatting with Prettier

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          # Prettier CLI arguments
          prettier_options: --check ./app
